title: dave's doing data 
author: dave456
email: dwild000@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm quite new to github and mostly everything else. Got a little experience in C, learning python especially for analysing data. 
  
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: fals # set to false to remove excerpts on the homepage
